version: 2

models:
  - name: dim_listings_cleansed
    config:
      tags: novo # Aqui está a tag 'novo'
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        tests:
          - accepted_values:
              
              values:
                ["Entire home/apt b", "Private room", "Shared room", "Hotel room"]
              config:
                severity: warn
      
      - name: minimum_nights
        tests: 
          - positive_value


  - name: dim_hosts_cleansed
    description: "Table content de hosts refined information "
    config:
      tags: novo # Aqui está a tag 'novo'
    columns:
      - name: HOST_ID
        description: "a unique id for hosts"
        tests:
          - unique
          - not_null

      