version: 2

sources:
  - name: techfriday
    database: TECHFRIDAY
    schema:  RAW_ADVENTURE_WORKS

    tables:
      - name: HUMAN_RESOURCES_DEPARTMENT
      - name: HUMAN_RESOURCES_EMPLOYEE
      - name: HUMAN_RESOURCES_EMPLOYEEDEPARTMENTHISTORY
      - name: HUMAN_RESOURCES_EMPLOYEEPAYHISTORY
      - name: HUMAN_RESOURCES_JOBCANDIDATE
      - name: HUMAN_RESOURCES_SHIFT
      - name: PERSON_ADDRESS
      - name: PERSON_ADDRESSTYPE
      - name: PERSON_BUSINESSENTITY
      - name: PERSON_BUSINESSENTITYADDRESS
      - name: PERSON_BUSINESSENTITYCONTACT
      - name: PERSON_CONTACTTYPE
      - name: PERSON_COUNTRYREGION
      - name: PERSON_EMAILADDRESS
      - name: PERSON_PERSON
      - name: PERSON_PERSONPHONE
      - name: PERSON_PHONENUMBERTYPE
      - name: PERSON_STATEPROVINCE
      - name: PRODUCTION_BILLOFMATERIALS
      - name: PRODUCTION_CULTURE
      - name: PRODUCTION_ILLUSTRATION
      - name: PRODUCTION_LOCATION
      - name: PRODUCTION_PRODUCT
      - name: PRODUCTION_PRODUCTCATEGORY
      - name: PRODUCTION_PRODUCTCOSTHISTORY
      - name: PRODUCTION_PRODUCTDESCRIPTION
      - name: PRODUCTION_PRODUCTDOCUMENT
      - name: PRODUCTION_PRODUCTINVENTORY
      - name: PRODUCTION_PRODUCTLISTPRICEHISTORY
      - name: PRODUCTION_PRODUCTMODEL
      - name: PRODUCTION_PRODUCTMODELILLUSTRATION
      - name: PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE
      - name: PRODUCTION_PRODUCTPRODUCTPHOTO
      - name: PRODUCTION_PRODUCTSUBCATEGORY
      - name: PRODUCTION_SCRAPREASON
      - name: PRODUCTION_TRANSACTIONHISTORY
      - name: PRODUCTION_TRANSACTIONHISTORYARCHIVE
      - name: PRODUCTION_UNITMEASURE
      - name: PRODUCTION_WORKORDER
      - name: PRODUCTION_WORKORDERROUTING
      - name: PURCHASING_PRODUCTVENDOR
      - name: PURCHASING_PURCHASEORDERDETAIL
      - name: PURCHASING_PURCHASEORDERHEADER
      - name: PURCHASING_SHIPMETHOD
      - name: PURCHASING_VENDOR
      - name: SALES_COUNTRYREGIONCURRENCY
      - name: SALES_CREDITCARD
      - name: SALES_CURRENCY
      - name: SALES_CURRENCYRATE
      - name: SALES_CUSTOMER
      - name: SALES_PERSONCREDITCARD
      - name: SALES_SALESORDERDETAIL
      - name: SALES_SALESORDERHEADER
      - name: SALES_SALESORDERHEADERSALESREASON
      - name: SALES_SALESPERSON
      - name: SALES_SALESPERSONQUOTAHISTORY
      - name: SALES_SALESREASON
      - name: SALES_SALESTAXRATE
      - name: SALES_SALESTERRITORY
      - name: SALES_SALESTERRITORYHISTORY
      - name: SALES_SHOPPINGCARTITEM
      - name: SALES_SPECIALOFFER
      - name: SALES_SPECIALOFFERPRODUCT
      - name: SALES_STORE